/**
 * API types: generated OpenAPI paths + hand-maintained response contracts.
 *
 * Regenerate: `npm run generate:api` from web/ (requires repo .venv).
 */

export type { components, operations, paths } from './schema.gen'
export type {
  AudioListResponse,
  LibraryListEnvelope,
  SchemaMeResponse,
  SchemaInstanceOrgCreateResponse,
  SchemaInstanceOrgListResponse,
  SchemaInstanceSettingsResponse,
  SchemaOrgCaptureJitsiResponse,
  SchemaOrgLedgerResponse,
  SchemaOrgPublicLinkListResponse,
  SchemaOrgPublicResponse,
  SchemaAuditLogListResponse,
  SchemaWorkerImpactResponse,
  SchemaWorkerDeleteResponse,
  SchemaWorkerProbeResponse,
  SchemaTariffDeleteImpactResponse,
  SchemaTariffDeleteResponse,
  SchemaDekListResponse,
  SchemaDekPublicResponse,
  SchemaEncryptionJobPublicResponse,
  SchemaEncryptionJobLatestResponse,
  SchemaSkillListResponse,
  SchemaSkillPublicResponse,
  SchemaCapturePlatformsResponse,
  SchemaImportPlatformsResponse,
  SchemaUserTagListResponse,
  SchemaPublicSummaryResponse,
  SchemaAudioCreatedResponse,
  SchemaOkStatusResponse,
  SchemaLoginOkResponse,
  SchemaLoginMfaRequiredResponse,
  SchemaOrgUserResetPasswordResponse,
  SchemaOrgUserListResponse,
  SchemaOrgSsoAdminResponse,
  SchemaUsageStatsResponse,
  SchemaInstanceUsageStatsResponse,
  SchemaTariffListResponse,
  SchemaTariffPublic,
  SchemaShareListResponse,
  SchemaUserPublic,
  SchemaWorkerListItem,
  SchemaWorkerListResponse,
  SchemaWorkerPublicResponse,
  SchemaAudioDetailResponse,
  SchemaAudioListResponse,
  SchemaSummaryDetailResponse,
  SchemaSummaryListResponse,
  SchemaTaskListItem,
  SchemaTaskListResponse,
  SchemaTaskPurgeResponse,
  SchemaTranscriptDetailResponse,
  SchemaTranscriptListResponse,
  SummaryListResponse,
  TaskListResponse,
  TranscriptListResponse,
} from './contracts'
